name: tabnews_flutter
description: A TabNews flutter front-end
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  provider: ^6.0.4
  flutter_session_manager: ^1.0.2
  timeago: ^3.3.0
  infinite_scroll_pagination: ^3.2.0
  json_serializable: ^6.5.4
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9+1
  markdown_editor_plus: ^0.2.13
  google_fonts: ^3.0.1
dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "tabnews-icon.png"
flutter:
  uses-material-design: true